spring:
  datasource:
    url: jdbc:mysql://8.130.113.69/travel_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 768260
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#  application:
#    name: springfox-swagger
#server:
#  port: 8080
## ===== 自定义swagger配置 ===== #
#swagger:
#  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: springfox swagger 3.0整合Demo
#  try-host: http://localhost:${server.port}

