spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/travel_system?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 768260
#logging:
#  level:
#    com.itheima: debug
#  pattern:
#    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
