spring:
  datasource:
    url: jdbc:mysql://8.130.113.69/travel_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 768260
#logging:
#  level:
#    com.itheima: debug
#  pattern:
#    dateformat: HH:mm:ss
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
